### ISSUE TITLE
Mario eval is slow

### ISSUE THREAD

**Issue by simoninithomas** [jcwleo/random-network-distillation-pytorch#19]
Hi @jcwleo,

Your implementation is amazing. I was currently searching for a simple but powerful implementation, I modified it a bit and train it with SuperMarioBros. However, when I want to eval my agent (using eval.py), the framerate is very slow.

Do you know why?

Thanks,
Have a nice day,

**Comment by jcwleo** [comment]
@simoninithomas 
Hi
I haven't tested it in a Super Mario environment yet. I will test and see if the same issue occurs.

**Comment by jcwleo** [comment]
@simoninithomas 
Hello. I catched issue. you can modify config of `use_cuda` on `eval.py`.
