### ISSUE TITLE
Generalized Advantage Estimator problem

### ISSUE THREAD

**Issue by RozenAstrayChen** [jcwleo/random-network-distillation-pytorch#25]
Hello I have problem in ```utils.py```.

in ```make_train_data```:

```python=
if use_gae:
        gae = np.zeros_like([num_worker, ])
        for t in range(num_step - 1, -1, -1):
            delta = reward[:, t] + gamma * value[:, t + 1] * (1 - done[:, t]) - value[:, t]
            gae = delta + gamma * lam * (1 - done[:, t]) * gae

            discounted_return[:, t] = gae + value[:, t]

            # For Actor
        adv = discounted_return - value[:, :-1]
```

I am confused, in my recognize gae is 

![2019-02-10 10 14 55](https://user-images.githubusercontent.com/19503080/52534831-5add6280-2d81-11e9-9020-b00d2d3b9c73.png)

![2019-02-10 10 13 03](https://user-images.githubusercontent.com/19503080/52534806-15b93080-2d81-11e9-86dd-2b6b75efabd6.png)

I haven't no idea why need to add V(t)
```python=
discounted_return[:, t] = gae + value[:, t]
```

Can you explain what I missing ? thx

**Comment by jcwleo** [comment]
@RozenAstrayChen 
Hi. 
Advantage definition is `A = Q - V`. and `GAE = Q - V` in use GAE.
so, `Q = GAE + V`. Q is used to update the value function.

**Comment by RozenAstrayChen** [comment]
Ok I have understand. I will close this issue , thx for your help!
