### ISSUE TITLE
input_size in model.py?

### ISSUE THREAD

**Issue by chaityabshah** [jcwleo/random-network-distillation-pytorch#29]
I'm working with a different env (other than atari or mario) and I want to change the input shape to the CNN. It seems like self.input_size is ignored? Do you have any explanation for the math going on when setting up the network (the parameters for each layer)? When I change the size from (84, 84) to anything else, I get size mismatch errors at the linear layer.

Thanks!

**Comment by jcwleo** [comment]
self.input_size may not work. If you want to make input size different, you can modify model parameters.
